#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-imagick
Version  : 3.7.0
Release  : 24
URL      : https://pecl.php.net/get/imagick-3.7.0.tgz
Source0  : https://pecl.php.net/get/imagick-3.7.0.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : PHP-3.01
Requires: php-imagick-lib = %{version}-%{release}
BuildRequires : ImageMagick-dev
BuildRequires : buildreq-php

%description
No detailed description available

%package dev
Summary: dev components for the php-imagick package.
Group: Development
Requires: php-imagick-lib = %{version}-%{release}
Provides: php-imagick-devel = %{version}-%{release}
Requires: php-imagick = %{version}-%{release}

%description dev
dev components for the php-imagick package.


%package lib
Summary: lib components for the php-imagick package.
Group: Libraries

%description lib
lib components for the php-imagick package.


%prep
%setup -q -n imagick-3.7.0
cd %{_builddir}/imagick-3.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/php/ext/imagick/php_imagick_shared.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20210902/imagick.so
