#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: phpize
# autospec version: v3
# autospec commit: c1050fe
#
Name     : php-imagick
Version  : 3.7.0
Release  : 66
URL      : https://pecl.php.net/get/imagick-3.7.0.tgz
Source0  : https://pecl.php.net/get/imagick-3.7.0.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : PHP-3.01
Requires: php-imagick-lib = %{version}-%{release}
Requires: php-imagick-license = %{version}-%{release}
BuildRequires : ImageMagick-dev
BuildRequires : buildreq-php
BuildRequires : perl(Getopt::Long)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the php-imagick package.
Group: Development
Requires: php-imagick-lib = %{version}-%{release}
Provides: php-imagick-devel = %{version}-%{release}
Requires: php-imagick = %{version}-%{release}

%description dev
dev components for the php-imagick package.


%package lib
Summary: lib components for the php-imagick package.
Group: Libraries
Requires: php-imagick-license = %{version}-%{release}

%description lib
lib components for the php-imagick package.


%package license
Summary: license components for the php-imagick package.
Group: Default

%description license
license components for the php-imagick package.


%prep
%setup -q -n imagick-3.7.0
cd %{_builddir}/imagick-3.7.0
pushd ..
cp -a imagick-3.7.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
mkdir -p %{buildroot}/usr/share/package-licenses/php-imagick
cp %{_builddir}/imagick-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/php-imagick/a1858e1db242bfbb45d60188d32289465bdc3c59 || :
%make_install

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/php/ext/imagick/php_imagick_shared.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20230831/imagick.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/php-imagick/a1858e1db242bfbb45d60188d32289465bdc3c59
